"""A tiny hand-written SMS-style dataset (original messages, for demo purposes only)."""

SPAM = [
    "WINNER!! You have been selected to receive a free prize. Claim now",
    "Congratulations! You won a $1000 gift card. Click the link to claim",
    "URGENT: your account has been suspended. Verify your password now",
    "Free entry in our weekly draw. Text WIN to 80085 to claim your prize",
    "Limited time offer: buy one get one free. Click here now",
    "You have been pre-approved for a cash loan. Apply now, no credit check",
    "Claim your free vacation to the Bahamas. Call now to win",
    "Act now! Exclusive deal, 90% off, free shipping. Click to claim",
    "Your package could not be delivered. Click the link to reschedule and pay a fee",
    "Earn $5000 a week working from home. Free guide, click now",
    "Final notice: you have won a free iPhone. Reply YES to claim the prize",
    "Cheap meds online, no prescription needed. Order now and save",
    "Get a free credit report and boost your score. Call now for a free quote",
    "Hot singles in your area want to chat. Click the link, it is free",
    "You are our lucky winner! Free cash prize waiting, claim today",
    "Bank alert: unusual activity detected. Verify your account details now",
    "Special promotion: win a free cruise. Text STOP to opt out",
    "Double your income now with this one weird trick. Click here, limited offer",
    "Free ringtones! Text TONE to 80123 to claim your free download",
    "Exclusive offer just for you: free gift with every order. Buy now",
    "Your loan is approved! Claim your cash now, call the number below",
    "Urgent response needed: claim your tax refund by clicking this link",
    "Win big! Free spins on our casino, no deposit needed. Claim now",
    "Lowest prices guaranteed. Free shipping on all orders, click to buy now",
    "Congratulations, you are a winner of our free holiday prize draw. Call to claim",
    "Please verify your password to avoid account suspension. Click the link now",
    "Make money fast! Free investment tips, guaranteed returns, act now",
    "FREE entry to win cash prizes every day. Text WIN now",
]

HAM = [
    "Hey, are we still meeting for lunch tomorrow?",
    "Can you pick up some milk on your way home?",
    "I'll be ten minutes late, traffic is terrible",
    "Thanks for dinner last night, it was lovely",
    "Don't forget mom's birthday is on Saturday",
    "Did you finish the report for the meeting this afternoon?",
    "Running late, start without me and I'll catch up",
    "What time does the movie start tonight?",
    "Happy birthday! Hope you have a wonderful day",
    "Can we reschedule our call to Thursday morning?",
    "I left my keys at your place, can I come get them later?",
    "The meeting has moved to room 4, see you there",
    "Great game last night! Let's play again next week",
    "Please send me the notes from yesterday's class",
    "I'm at the station, where are you parked?",
    "Just landed, I'll text you when I get to the hotel",
    "Do you want to grab coffee after work?",
    "Remember to bring the charger when you come over",
    "Sorry I missed your call, I was in a meeting",
    "Let me know when you've got the tickets sorted",
    "I'll call you tonight after the kids are in bed",
    "The doctor said everything looks fine, thanks for asking",
    "Can you review my code before the deadline on Friday?",
    "We're out of coffee at the office, who is going to the shop?",
    "See you at the gym at six, don't be late this time",
    "Thanks for helping me move, I owe you a pizza",
    "How was your trip? Send me some photos when you can",
    "Dinner is ready, come downstairs when you're done",
]
